### ISSUE TITLE
The email input field is distorted

### ISSUE THREAD

**Issue by edmondyu** [likecoin/likecoin-store#221] opened 2018-04-13 06:49 UTC
location: email verification message box
platform: iOS trust
![img_0224](https://user-images.githubusercontent.com/17264698/38720712-e514bd1e-3f29-11e8-92ae-25569e38b2dc.PNG)

**Comment by williamchong007** [comment] 2018-04-13 06:50
duplicate of https://github.com/likecoin/likecoin-store/issues/210

**Closed by williamchong007** 2018-04-13 06:50 UTC
